# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True)),
                ('valor', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Paises',
            },
        ),
    ]
